# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0035_merge_20190802_0954'),
        ('audiencia', '0011_auto_20190712_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienciapublica',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
    ]
