# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.audiencia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0063_auto_20191010_1228'),
        ('audiencia', '0012_audienciapublica_parlamentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienciapublica',
            name='requerimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimento', to='materia.MateriaLegislativa', verbose_name='Requerimento da Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='anexoaudienciapublica',
            name='arquivo',
            field=models.FileField(max_length=200, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Autor da Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.audiencia.models.anexo_upload_path, verbose_name='Anexo da Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='upload_ata',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.audiencia.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='upload_pauta',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.audiencia.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Audiência Pública'),
        ),
    ]
