# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20190417_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listabrancavotacao',
            unique_together=set([('ip',)]),
        ),
    ]
