# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20190417_1328'),
        ('base', '0036_auto_20190417_1432'),
    ]

    operations = [
    ]
